/**
 * PDF Export & Document Management
 * Generates printable/shareable PDF documents from legal templates
 */

const PDFExportModule = {
    // Generate PDF from document template
    generatePDF(category, caseData = {}) {
        const data = LEGAL_DATA[category];
        if (!data) return;

        const isHindi = currentLang === 'hi';
        const title = isHindi ? (data.title_hi || data.title) : data.title;
        const template = isHindi ? (data.document_template_hi || data.document_template) : data.document_template;

        // Create document content
        let content = `
================================================================================
                    ${title.toUpperCase()}
================================================================================

GENERATED BY: Haqqdar AI — India's Rights & Benefits Navigator
DOCUMENT TYPE: Legal Complaint / Application Template
GENERATED ON: ${new Date().toLocaleString()}
REFERENCE LAW: ${data.law}

================================================================================

${template}

================================================================================
NOTES:
- Replace all [PLACEHOLDERS] with actual information
- Keep 2 copies: one for submission, one for your records
- Obtain acknowledgment receipt from receiving authority
- Follow up within statutory deadline periods

ESCALATION CONTACTS:
${this.formatEscalation(data.escalation)}

USEFUL PORTALS:
${this.formatPortals(data.portals)}

================================================================================
This document was generated using Haqqdar AI. While generated by AI, the
content is based on verified Indian laws and constitutional provisions.
Always consult a qualified lawyer for specific legal advice.

For more help, visit: https://haqqdar.vercel.app
================================================================================
        `;

        return this.downloadAsFile(content, `${category}-${new Date().getTime()}.txt`, 'text/plain');
    },

    // Generate printable HTML version
    generatePrintableHTML(category) {
        const data = LEGAL_DATA[category];
        if (!data) return;

        const isHindi = currentLang === 'hi';
        const title = isHindi ? (data.title_hi || data.title) : data.title;
        const template = isHindi ? (data.document_template_hi || data.document_template) : data.document_template;
        
        const html = `
<!DOCTYPE html>
<html lang="${currentLang}">
<head>
    <meta charset="UTF-8">
    <title>${title} - Haqqdar</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body { 
            font-family: 'Arial', sans-serif; 
            line-height: 1.6; 
            color: #333; 
            padding: 40px;
            background: white;
        }
        .header {
            text-align: center;
            border-bottom: 3px solid #1e40af;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .header h1 { color: #1e40af; font-size: 24px; margin-bottom: 10px; }
        .header p { color: #666; font-size: 12px; }
        .law-ref { 
            background: #f0f9ff; 
            padding: 15px; 
            border-left: 4px solid #0284c7;
            margin: 20px 0;
            font-size: 13px;
        }
        .rights-box {
            background: #f8fafc;
            padding: 20px;
            border-radius: 8px;
            margin: 20px 0;
            border: 1px solid #e2e8f0;
        }
        .rights-box h3 { color: #1e40af; margin-bottom: 10px; }
        .rights-box ul { margin-left: 20px; }
        .rights-box li { margin-bottom: 8px; }
        .template-section {
            background: #fff9e6;
            padding: 25px;
            margin: 20px 0;
            border: 1px solid #fbbf24;
            font-family: 'Courier New', monospace;
            font-size: 12px;
            white-space: pre-wrap;
            word-wrap: break-word;
        }
        .escalation-table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        .escalation-table th, .escalation-table td {
            border: 1px solid #cbd5e1;
            padding: 12px;
            text-align: left;
        }
        .escalation-table th { background: #1e40af; color: white; }
        .escalation-table tr:nth-child(even) { background: #f8fafc; }
        .footer {
            margin-top: 40px;
            padding-top: 20px;
            border-top: 2px solid #e2e8f0;
            font-size: 11px;
            color: #666;
            text-align: center;
        }
        .watermark {
            position: fixed;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%) rotate(-45deg);
            font-size: 80px;
            opacity: 0.05;
            z-index: 0;
        }
        @media print {
            body { padding: 0; }
            * { box-shadow: none !important; }
        }
    </style>
</head>
<body>
    <div class="watermark">Haqqdar</div>
    <div class="header">
        <h1>⚖️ ${title}</h1>
        <p>Generated by Haqqdar AI • ${new Date().toLocaleString()}</p>
    </div>
    
    <div class="law-ref">
        <strong>Applicable Law:</strong> ${data.law}
    </div>
    
    <div class="rights-box">
        <h3>📜 Your Legal Rights</h3>
        <ul>
            ${data.rights.map(r => `<li>${r}</li>`).join('')}
        </ul>
    </div>
    
    <h3 style="margin-top: 30px; color: #1e40af;">📄 Document Template</h3>
    <div class="template-section">${template}</div>
    
    <h3 style="margin-top: 30px; color: #1e40af;">🔼 Escalation Ladder</h3>
    <table class="escalation-table">
        <thead>
            <tr>
                <th>Level</th>
                <th>Action</th>
                <th>Description</th>
            </tr>
        </thead>
        <tbody>
            ${data.escalation.map(e => `
                <tr>
                    <td>${e.level}</td>
                    <td>${e.title}</td>
                    <td>${e.desc}</td>
                </tr>
            `).join('')}
        </tbody>
    </table>
    
    <div class="footer">
        <p><strong>⚠️ Important:</strong> This document contains legal information generated by AI, not legal advice. 
        Replace all [PLACEHOLDERS] with actual information before submission. 
        Always consult a qualified lawyer for complex legal matters.</p>
        <p>Haqqdar AI • Making Rights Accessible to Every Indian • https://haqqdar.vercel.app</p>
    </div>
</body>
</html>
        `;

        const blob = new Blob([html], { type: 'text/html' });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = `${category}-printable-${new Date().getTime()}.html`;
        a.click();
        window.URL.revokeObjectURL(url);
    },

    // Email document (requires backend)
    async emailDocument(category, email) {
        const data = LEGAL_DATA[category];
        if (!data) return;

        try {
            const response = await fetch('/api/send-document', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    category,
                    email,
                    title: data.title,
                    template: data.document_template,
                    timestamp: new Date().toISOString()
                })
            });

            if (response.ok) {
                alert(currentLang === 'hi' 
                    ? '✓ दस्तावेज़ ईमेल किया गया' 
                    : '✓ Document emailed successfully');
            }
        } catch (error) {
            console.error('Email error:', error);
            alert(currentLang === 'hi'
                ? '❌ ईमेल भेजने में विफल'
                : '❌ Failed to email document');
        }
    },

    // Format escalation for display
    formatEscalation(escalation) {
        return escalation.map(e => `
Level ${e.level}: ${e.title}
${e.desc}
${e.link ? `Portal: ${e.link}` : ''}
`).join('\n');
    },

    // Format portals for display
    formatPortals(portals) {
        if (!portals) return '';
        return Object.entries(portals).map(([name, link]) => 
            `${name}: ${link}`
        ).join('\n');
    },

    // Download file helper
    downloadAsFile(content, filename, mimeType = 'text/plain') {
        const blob = new Blob([content], { type: mimeType });
        const url = window.URL.createObjectURL(blob);
        const a = document.createElement('a');
        a.href = url;
        a.download = filename;
        document.body.appendChild(a);
        a.click();
        document.body.removeChild(a);
        window.URL.revokeObjectURL(url);
    }
};

// Export module for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = PDFExportModule;
}
